### ISSUE TITLE
Reading records fails

### ISSUE THREAD

**Issue by GaetanColenoTiime** [mtxr/vscode-sqltools#1343]
**Describe the bug**
When i try to see records of a table, whatever the way, i can't, and here is the error :

[1717968897729] ERROR (TypeError):
    TypeError: Cannot read properties of undefined (reading 'total')
        at li.<anonymous> (/home/vscode/.vscode-server/extensions/mtxr.sqltools-driver-pg-0.5.4/out/ls/plugin.js:118:17015)
        at Generator.next (<anonymous>)
        at a (/home/vscode/.vscode-server/extensions/mtxr.sqltools-driver-pg-0.5.4/out/ls/plugin.js:118:15544)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1717968897730] ERROR (ext): ERROR: Execute query error Cannot read properties of undefined (reading 'total'), 'Cannot read properties of undefined (reading 'total')'
    ns: "error-handler"
[1717968897730] ERROR (ext): ERROR: Error while showing table records Cannot read properties of undefined (reading 'total'), {"code":-1,"data":{"driver":"PostgreSQL","driverOptions":{}}}
    ns: "error-handler"

And a window open with infinite loading screen

**To Reproduce**
1. Go to SQLTools extension tab, on any table you want
2. Click on show table records
3. See error

**Expected behavior**
See the actuals records of the table

**Screenshots**
![image](https://github.com/mtxr/vscode-sqltools/assets/103251803/40e0a0e8-c8c7-4ae0-aa34-c0d55d8654f0)

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x] v0.28.3
 - VS Code Version: [e.g 1.x.y] v1.90.0
 - OS: [e.g. Windows, Linux, Mac] Windows (in devcontainer debian)
 - Driver:
   - [X] PostgreSQL/Redshift v0.5.4
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...] Postgresql 16

**Additional context**

**Comment by bcheung** [comment]
I'm also having this issue. Using Neon database if that matters/helps with context
