### ISSUE TITLE
Extension 'mtxr.sqltools' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'document')

### ISSUE THREAD

**Issue by sjordan1975** [mtxr/vscode-sqltools#1376]
**Describe the bug**
Opened VSCode today and started seeing the following error in the Output tab of the terminal:

`
[ExtensionListenerError] Extension 'mtxr.sqltools' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'document'): Error: [ExtensionListenerError] Extension 'mtxr.sqltools' FAILED to handle event: TypeError: Cannot read properties of undefined (reading 'document')
    at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:28731)
    at r.B (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
    at r.C (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
    at c.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:34921)
    at y.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:5968)
    at y.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:5734)
    at y.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4767)
    at y.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:3602)
    at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:2297)
    at r.B (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
    at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:184:8635)
    at r.B (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:184:6761)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)
`

**To Reproduce**
1. Open VS Code
2. Open Terminal
3. Go to Output tab

**Expected behavior**
Not to see this error

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [v0.28.3]
 - VS Code Version: [1.93.0]
 - OS: [Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [X] SQLite
   - [ ] Other? Which...
 - Database version: [not applicable as I was not attempting to connect to any database]

**Additional context**
Note, this was not any specific attempt to connect to a database. Simply opening VSCode throws this error

**Comment by gjsjohnmurray** [comment]
Which channel of the Output tab on Panel is selected when that error displays?

Does the SQLTools channel of Output show information about the extension initializing?

Does the problem also occur when you open a new VS Code window with no folder/file(s)/workspace opened?

**Comment by sjordan1975** [comment]
Update: I disable both sqltools and sqltool sqllite driver. Closed VSCode overnight. Re-enabled the plugins and now I am not seeing the error. I don't know what else changed.

I'll report back if I re-encounter the error.

**Comment by gjsjohnmurray** [comment]
Thanks for the update. Closing for the moment.

**Comment by TonyGravagno** [comment]
Please re-open ticket.

Running SQLTools v0.28.3 from 2024-11-12. Still getting this error over latest VSCode 1.95.3/Windows.

I disabled primary extension and drivers. Completely restarted VSCode, no error. Enabled primary extension, no drivers, got same "reading 'document'" error in Extension Host output window. No driver enabled, no documents open.

I'm happy to help diagnose this if I can.

**Comment by TonyGravagno** [comment]
I'm doing extension cleanup and wanted to see if I could find anything more about this anomaly.
I disabled all extensions and I'm re-enabling them one by one. As I do this I have my Extension Host output window open in a separate window - easier to see - as exthost.log.
With this one .log window open I enabled SQLTools and it goes into what seems like an infinite loop on this error.
Note, this is simply when VSCode is opened and there is no folder or workspace open, no files in Explorer, etc.

I hope that helps.

**Comment by tobiashochguertel** [comment]
```
2025-03-15 15:45:54.589 [error] ExtensionError: Error in extension mtxr.sqltools: FAILED to handle event
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:35559)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2445)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2662)
    at lW.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:63847)
    at qy.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116244)
    at qy.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116024)
    at qy.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115113)
    at qy.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114218)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113015)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:13324)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:11616)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

```
2025-03-15 15:45:55.205 [error] ExtensionError: Error in extension mtxr.sqltools: FAILED to handle event
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:35559)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2445)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2662)
    at lW.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:63847)
    at qy.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116244)
    at qy.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116024)
    at qy.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115113)
    at qy.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114218)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113015)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:13324)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:11616)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

```
2025-03-15 15:45:55.564 [error] ExtensionError: Error in extension mtxr.sqltools: FAILED to handle event
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:35559)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2445)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2662)
    at lW.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:63847)
    at qy.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116244)
    at qy.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116024)
    at qy.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115113)
    at qy.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114218)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113015)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:13324)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:11616)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

```
2025-03-15 15:45:55.966 [error] ExtensionError: Error in extension mtxr.sqltools: FAILED to handle event
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:35559)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2445)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2662)
    at lW.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:63847)
    at qy.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116244)
    at qy.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116024)
    at qy.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115113)
    at qy.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114218)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113015)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at Th.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:13324)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2375)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2593)
    at Gn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9459)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:190:11616)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
```

.... I get this error in the `Extension Host` Output Channel, when I start VSCode / a new Window. 

In the extension Features, I can see this:

```
Runtime Status
Activation
Activated on Startup: 2ms

Uncaught Errors (88)
 Error in extension mtxr.sqltools: FAILED to handle event
 Error in extension mtxr.sqltools: FAILED to handle event
 Error in extension mtxr.sqltools: FAILED to handle event
 Error in extension mtxr.sqltools: FAILED to handle event
 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event

 Error in extension mtxr.sqltools: FAILED to handle event
```
