### ISSUE TITLE
Can't connect to MySQL8

### ISSUE THREAD

**Issue by rectcircle** [mtxr/vscode-sqltools#173]
## Can't connect to MySQL8
![image](https://user-images.githubusercontent.com/18106246/55713377-20134600-5a23-11e9-96b0-b7d318cc103b.png)
![image](https://user-images.githubusercontent.com/18106246/55713480-55b82f00-5a23-11e9-99d0-82e8cfc7ab10.png)

## Log output

```log
Request connection/RefreshAllRequest received
Error:  { Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'C.TABLE_NAME' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.module.exports.Sequence._packetToError (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:20402:13)
    at Query.module.exports.Query.ErrorPacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89604:18)
    at Protocol.module.exports.Protocol._parsePacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170743:23)
    at Parser.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:171013:12)
    at Protocol.module.exports.Protocol.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170498:16)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43110:28)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43529:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Pool.module.exports.Pool.query (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89948:23)
    at Promise (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170141:14)
    at new Promise (<anonymous>)
    at open.then.conn (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170140:14)
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage:
   'Expression #1 of ORDER BY clause is not in SELECT list, references column \'C.TABLE_NAME\' which is not in SELECT list; this is incompatible with DISTINCT',
  sqlState: 'HY000',
  index: 0,
  sql:
   '\nSELECT\n  DISTINCT C.TABLE_NAME AS tableName,\n  C.COLUMN_NAME AS columnName,\n  C.DATA_TYPE AS type,\n  C.CHARACTER_MAXIMUM_LENGTH AS size,\n  C.TABLE_SCHEMA as tableSchema,\n  C.TABLE_CATALOG AS tableCatalog,\n  DATABASE() as tableDatabase,\n  C.COLUMN_DEFAULT as defaultValue,\n  C.IS_NULLABLE as isNullable,\n  C.ORDINAL_POSITION,\n  (\n    CASE\n      WHEN C.COLUMN_KEY = \'PRI\' THEN TRUE\n      ELSE FALSE\n    END\n  ) as isPk,\n  (\n    CASE\n      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE\n      ELSE TRUE\n    END\n  ) as isFk,\n  CONCAT(\n    C.TABLE_SCHEMA,\n    \'/\',\n    (\n      CASE\n        WHEN T.TABLE_TYPE = \'VIEW\' THEN \'views\'\n        ELSE \'tables\'\n      END\n    ),\n    \'/\',\n    C.TABLE_name,\n    \'/\',\n    C.COLUMN_NAME\n  ) AS tree\nFROM\n  INFORMATION_SCHEMA.COLUMNS AS C\n  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (\n    C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.TABLE_NAME = KCU.TABLE_NAME\n    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA\n    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.COLUMN_NAME = KCU.COLUMN_NAME\n  )\n  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME\n  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA\n  AND C.TABLE_CATALOG = T.TABLE_CATALOG\nWHERE\n  C.TABLE_SCHEMA = DATABASE()\nORDER BY\n  C.TABLE_NAME,\n  C.ORDINAL_POSITION' }
Request connection/RefreshAllRequest received
Error:  { Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'C.TABLE_NAME' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.module.exports.Sequence._packetToError (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:20402:13)
    at Query.module.exports.Query.ErrorPacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89604:18)
    at Protocol.module.exports.Protocol._parsePacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170743:23)
    at Parser.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:171013:12)
    at Protocol.module.exports.Protocol.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170498:16)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43110:28)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43529:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Pool.module.exports.Pool.query (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89948:23)
    at Promise (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170141:14)
    at new Promise (<anonymous>)
    at open.then.conn (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170140:14)
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage:
   'Expression #1 of ORDER BY clause is not in SELECT list, references column \'C.TABLE_NAME\' which is not in SELECT list; this is incompatible with DISTINCT',
  sqlState: 'HY000',
  index: 0,
  sql:
   '\nSELECT\n  DISTINCT C.TABLE_NAME AS tableName,\n  C.COLUMN_NAME AS columnName,\n  C.DATA_TYPE AS type,\n  C.CHARACTER_MAXIMUM_LENGTH AS size,\n  C.TABLE_SCHEMA as tableSchema,\n  C.TABLE_CATALOG AS tableCatalog,\n  DATABASE() as tableDatabase,\n  C.COLUMN_DEFAULT as defaultValue,\n  C.IS_NULLABLE as isNullable,\n  C.ORDINAL_POSITION,\n  (\n    CASE\n      WHEN C.COLUMN_KEY = \'PRI\' THEN TRUE\n      ELSE FALSE\n    END\n  ) as isPk,\n  (\n    CASE\n      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE\n      ELSE TRUE\n    END\n  ) as isFk,\n  CONCAT(\n    C.TABLE_SCHEMA,\n    \'/\',\n    (\n      CASE\n        WHEN T.TABLE_TYPE = \'VIEW\' THEN \'views\'\n        ELSE \'tables\'\n      END\n    ),\n    \'/\',\n    C.TABLE_name,\n    \'/\',\n    C.COLUMN_NAME\n  ) AS tree\nFROM\n  INFORMATION_SCHEMA.COLUMNS AS C\n  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (\n    C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.TABLE_NAME = KCU.TABLE_NAME\n    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA\n    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.COLUMN_NAME = KCU.COLUMN_NAME\n  )\n  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME\n  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA\n  AND C.TABLE_CATALOG = T.TABLE_CATALOG\nWHERE\n  C.TABLE_SCHEMA = DATABASE()\nORDER BY\n  C.TABLE_NAME,\n  C.ORDINAL_POSITION' }
Request connection/RefreshAllRequest received
Request connection/RefreshAllRequest received
Request connection/RefreshAllRequest received
Error:  { Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'C.TABLE_NAME' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.module.exports.Sequence._packetToError (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:20402:13)
    at Query.module.exports.Query.ErrorPacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89604:18)
    at Protocol.module.exports.Protocol._parsePacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170743:23)
    at Parser.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:171013:12)
    at Protocol.module.exports.Protocol.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170498:16)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43110:28)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43529:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Pool.module.exports.Pool.query (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89948:23)
    at Promise (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170141:14)
    at new Promise (<anonymous>)
    at open.then.conn (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170140:14)
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage:
   'Expression #1 of ORDER BY clause is not in SELECT list, references column \'C.TABLE_NAME\' which is not in SELECT list; this is incompatible with DISTINCT',
  sqlState: 'HY000',
  index: 0,
  sql:
   '\nSELECT\n  DISTINCT C.TABLE_NAME AS tableName,\n  C.COLUMN_NAME AS columnName,\n  C.DATA_TYPE AS type,\n  C.CHARACTER_MAXIMUM_LENGTH AS size,\n  C.TABLE_SCHEMA as tableSchema,\n  C.TABLE_CATALOG AS tableCatalog,\n  DATABASE() as tableDatabase,\n  C.COLUMN_DEFAULT as defaultValue,\n  C.IS_NULLABLE as isNullable,\n  C.ORDINAL_POSITION,\n  (\n    CASE\n      WHEN C.COLUMN_KEY = \'PRI\' THEN TRUE\n      ELSE FALSE\n    END\n  ) as isPk,\n  (\n    CASE\n      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE\n      ELSE TRUE\n    END\n  ) as isFk,\n  CONCAT(\n    C.TABLE_SCHEMA,\n    \'/\',\n    (\n      CASE\n        WHEN T.TABLE_TYPE = \'VIEW\' THEN \'views\'\n        ELSE \'tables\'\n      END\n    ),\n    \'/\',\n    C.TABLE_name,\n    \'/\',\n    C.COLUMN_NAME\n  ) AS tree\nFROM\n  INFORMATION_SCHEMA.COLUMNS AS C\n  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (\n    C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.TABLE_NAME = KCU.TABLE_NAME\n    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA\n    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.COLUMN_NAME = KCU.COLUMN_NAME\n  )\n  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME\n  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA\n  AND C.TABLE_CATALOG = T.TABLE_CATALOG\nWHERE\n  C.TABLE_SCHEMA = DATABASE()\nORDER BY\n  C.TABLE_NAME,\n  C.ORDINAL_POSITION' }
Error:  { Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'C.TABLE_NAME' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.module.exports.Sequence._packetToError (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:20402:13)
    at Query.module.exports.Query.ErrorPacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89604:18)
    at Protocol.module.exports.Protocol._parsePacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170743:23)
    at Parser.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:171013:12)
    at Protocol.module.exports.Protocol.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170498:16)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43110:28)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43529:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Pool.module.exports.Pool.query (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89948:23)
    at Promise (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170141:14)
    at new Promise (<anonymous>)
    at open.then.conn (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170140:14)
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage:
   'Expression #1 of ORDER BY clause is not in SELECT list, references column \'C.TABLE_NAME\' which is not in SELECT list; this is incompatible with DISTINCT',
  sqlState: 'HY000',
  index: 0,
  sql:
   '\nSELECT\n  DISTINCT C.TABLE_NAME AS tableName,\n  C.COLUMN_NAME AS columnName,\n  C.DATA_TYPE AS type,\n  C.CHARACTER_MAXIMUM_LENGTH AS size,\n  C.TABLE_SCHEMA as tableSchema,\n  C.TABLE_CATALOG AS tableCatalog,\n  DATABASE() as tableDatabase,\n  C.COLUMN_DEFAULT as defaultValue,\n  C.IS_NULLABLE as isNullable,\n  C.ORDINAL_POSITION,\n  (\n    CASE\n      WHEN C.COLUMN_KEY = \'PRI\' THEN TRUE\n      ELSE FALSE\n    END\n  ) as isPk,\n  (\n    CASE\n      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE\n      ELSE TRUE\n    END\n  ) as isFk,\n  CONCAT(\n    C.TABLE_SCHEMA,\n    \'/\',\n    (\n      CASE\n        WHEN T.TABLE_TYPE = \'VIEW\' THEN \'views\'\n        ELSE \'tables\'\n      END\n    ),\n    \'/\',\n    C.TABLE_name,\n    \'/\',\n    C.COLUMN_NAME\n  ) AS tree\nFROM\n  INFORMATION_SCHEMA.COLUMNS AS C\n  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (\n    C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.TABLE_NAME = KCU.TABLE_NAME\n    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA\n    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.COLUMN_NAME = KCU.COLUMN_NAME\n  )\n  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME\n  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA\n  AND C.TABLE_CATALOG = T.TABLE_CATALOG\nWHERE\n  C.TABLE_SCHEMA = DATABASE()\nORDER BY\n  C.TABLE_NAME,\n  C.ORDINAL_POSITION' }
Error:  { Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'C.TABLE_NAME' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.module.exports.Sequence._packetToError (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:20402:13)
    at Query.module.exports.Query.ErrorPacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89604:18)
    at Protocol.module.exports.Protocol._parsePacket (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170743:23)
    at Parser.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:171013:12)
    at Protocol.module.exports.Protocol.write (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170498:16)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43110:28)
    at Socket.<anonymous> (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:43529:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    --------------------
    at Pool.module.exports.Pool.query (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:89948:23)
    at Promise (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170141:14)
    at new Promise (<anonymous>)
    at open.then.conn (/Users/xxx/.vscode/extensions/mtxr.sqltools-0.17.11/languageserver.js:170140:14)
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage:
   'Expression #1 of ORDER BY clause is not in SELECT list, references column \'C.TABLE_NAME\' which is not in SELECT list; this is incompatible with DISTINCT',
  sqlState: 'HY000',
  index: 0,
  sql:
   '\nSELECT\n  DISTINCT C.TABLE_NAME AS tableName,\n  C.COLUMN_NAME AS columnName,\n  C.DATA_TYPE AS type,\n  C.CHARACTER_MAXIMUM_LENGTH AS size,\n  C.TABLE_SCHEMA as tableSchema,\n  C.TABLE_CATALOG AS tableCatalog,\n  DATABASE() as tableDatabase,\n  C.COLUMN_DEFAULT as defaultValue,\n  C.IS_NULLABLE as isNullable,\n  C.ORDINAL_POSITION,\n  (\n    CASE\n      WHEN C.COLUMN_KEY = \'PRI\' THEN TRUE\n      ELSE FALSE\n    END\n  ) as isPk,\n  (\n    CASE\n      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE\n      ELSE TRUE\n    END\n  ) as isFk,\n  CONCAT(\n    C.TABLE_SCHEMA,\n    \'/\',\n    (\n      CASE\n        WHEN T.TABLE_TYPE = \'VIEW\' THEN \'views\'\n        ELSE \'tables\'\n      END\n    ),\n    \'/\',\n    C.TABLE_name,\n    \'/\',\n    C.COLUMN_NAME\n  ) AS tree\nFROM\n  INFORMATION_SCHEMA.COLUMNS AS C\n  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (\n    C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.TABLE_NAME = KCU.TABLE_NAME\n    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA\n    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG\n    AND C.COLUMN_NAME = KCU.COLUMN_NAME\n  )\n  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME\n  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA\n  AND C.TABLE_CATALOG = T.TABLE_CATALOG\nWHERE\n  C.TABLE_SCHEMA = DATABASE()\nORDER BY\n  C.TABLE_NAME,\n  C.ORDINAL_POSITION' }
```

**Format SQL**

```sql
SELECT
  DISTINCT C.TABLE_NAME AS tableName,
  C.COLUMN_NAME AS columnName,
  C.DATA_TYPE AS type,
  C.CHARACTER_MAXIMUM_LENGTH AS size,
  C.TABLE_SCHEMA as tableSchema,
  C.TABLE_CATALOG AS tableCatalog,
  DATABASE() as tableDatabase,
  C.COLUMN_DEFAULT as defaultValue,
  C.IS_NULLABLE as isNullable,
  C.ORDINAL_POSITION,
  (
    CASE
      WHEN C.COLUMN_KEY = 'PRI' THEN TRUE
      ELSE FALSE
    END
  ) as isPk,
  (
    CASE
      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE
      ELSE TRUE
    END
  ) as isFk,
  CONCAT(
    C.TABLE_SCHEMA,
    '/',
    (
      CASE
        WHEN T.TABLE_TYPE = 'VIEW' THEN 'views'
        ELSE 'tables'
      END
    ),
    '/',
    C.TABLE_name,
    '/',
    C.COLUMN_NAME
  ) AS tree
FROM
  INFORMATION_SCHEMA.COLUMNS AS C
  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (
    C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.TABLE_NAME = KCU.TABLE_NAME
    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.COLUMN_NAME = KCU.COLUMN_NAME
  )
  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME
  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
  AND C.TABLE_CATALOG = T.TABLE_CATALOG
WHERE
  C.TABLE_SCHEMA = DATABASE()
ORDER BY
  C.TABLE_NAME,
  C.ORDINAL_POSITION
```

## Reference

> [to see](https://stackoverflow.com/questions/34691059/select-distinct-and-order-by-in-mysql)

## Reason

After version 5.7 of mysql, if DISTINCT and order by are used together, 3065 errors will be reported and SQL statements cannot be executed. The latest version of MySQL 5.7 grammar is more stringent than the previous version of 5.6 grammar. Both DISTINCT and order by sort the data, so there will be conflicts.

if Add the following configuration, it will run normally

```ini
[mysqld] 
# ...
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
```

**Desktop (please complete the following information):**
 - OS: Mac
 - SQLTools Version v0.17.11

**Comment by mtxr** [comment]
@rectcircle if you run this query without the distinct, which results do you get?

I believe it will work.

Anyway I'm using MySQL 8.0.15 locally and it works with both queries, I believe the flag is already active in my docker image.

Thanks
