### ISSUE TITLE
Not Connecting to MSSQL Server

### ISSUE THREAD

**Issue by Profesor08** [mtxr/vscode-sqltools#181]
**Describe the bug**
When I add an connection to existing and running mssql server and trying to connect - nothing happens. No errors.

**To Reproduce**
1. Install MS SQL Express
2. Run MS SQL
3. Install Extension 
4. Add Connection
5. Try to connect

**Expected behavior**
Something to happen or to show open connection, or some error, or something else to show a working.

**Screenshots**
https://i.imgur.com/MXHzm8j.png
https://i.imgur.com/MbrsSvZ.png
https://i.imgur.com/CuUcxL9.png

**Desktop (please complete the following information):**
 - Windows 10
 - SQLTools Version v0.17.12, v0.17.13. I dont checked more.

**Additional context**
MS SQL Server Express is working fine, I can browse it with SQL Server Management Studio, I can run game server, I can connect and work from developing application.

**Comment by mtxr** [comment]
Can you check the errors on output channel?

**Comment by Profesor08** [comment]
There is nothing about SQL

**Comment by Profesor08** [comment]
> Can you check the errors on output channel?

There is nothing about SQL

**Comment by mtxr** [comment]
![image](https://user-images.githubusercontent.com/707561/55928524-5b627000-5bef-11e9-9f37-b24a9ef73e35.png)

You don't have this option?

This channel should provide all necessary log for me to fix this issue.

**Comment by briansix** [comment]
My previously working connections have also begin failing, and could be the same problem. I reinstalled vscode and the extension, still happening.

_Mac, VS Code 1.33.0, SQLTools v0.17, SQL Server 2012, authenticating with AD account using domain._ 

Steps to recreate:

Create or right-click existing connection, select connect. 

Prompt error: 

> Error while preparing columns completions for connection CONSMRTPRD Request connection/ConnectionDataUpdatedRequest failed with message: Cannot read property '$$' of undefined
Would you like to see the logs?
Source: SQLTools (Extension)

Select yes, here is output: 

```
Request connection/ConnectRequest received
###### Attention ######
getFunctions not implemented for MSSQL
####################
Error:  { Error: Request connection/ConnectionDataUpdatedRequest failed with message: Cannot read property '$$' of undefined
    at handleResponse (/Users/bb012358/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:13042:36)
    at processMessageQueue (/Users/bb012358/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:12866:9)
    at Immediate.setImmediate (/Users/bb012358/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:12849:7)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5) code: -32603, data: undefined }
```

**Comment by briansix** [comment]
My previously working connections have also begin failing, and could be the same problem. I reinstalled vscode and the extension, still happening.

_Mac, VS Code 1.33.0, SQLTools v0.17, SQL Server 2012, authenticating with AD account using domain._ 

Steps to recreate:

Create or right-click existing connection, select connect. 

Prompt error: 

> Error while preparing columns completions for connection MSSQLPRD01 Request connection/ConnectionDataUpdatedRequest failed with message: Cannot read property '$$' of undefined
Would you like to see the logs?
Source: SQLTools (Extension)

Select yes, here is output: 

```
Request connection/ConnectRequest received
###### Attention ######
getFunctions not implemented for MSSQL
####################
Error:  { Error: Request connection/ConnectionDataUpdatedRequest failed with message: Cannot read property '$$' of undefined
    at handleResponse (/Users/brian/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:13042:36)
    at processMessageQueue (/Users/brian/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:12866:9)
    at Immediate.setImmediate (/Users/brian/.vscode/extensions/mtxr.sqltools-0.17.13/languageserver.js:12849:7)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5) code: -32603, data: undefined }
```

**Comment by Romboter** [comment]
I'm seeing similar while trying to connect to a SQL 2012 server.
Windows 10
VS Code 1.33
SQLTools 0.17.13

The output only shows this
INFO: Executing SQLTools.openAddConnectionScreen
INFO: Executing SQLTools.addConnection
DEBUG: Configs reloaded!
INFO: Executing SQLTools.selectConnection

I am able to connect to this server via the SQL Server (mssql) extension and other tools.

**Comment by mtxr** [comment]
Ok, thanks you guys.

I'll take a look after the job.

**Comment by Profesor08** [comment]
Output for SQLTools is:
`INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection`

Output for SQLTools Language Server is:
`Request connection/ConnectRequest received
(node:9796) UnhandledPromiseRejectionWarning: TypeError: The "config.authentication.options.domain" property must be of type string.
    at new Connection (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:110957:19)
    at base.Promise (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:109184:23)
    at new Promise (<anonymous>)
    at ConnectionPool._poolCreate (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:109145:12)
    at ConnectionPool._connect (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:154325:10)
    at PromiseLibrary (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:154301:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:154300:12)
    at Promise (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:108678:14)
    at new Promise (<anonymous>)
(node:9796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)`

As you can see, the we have an error. And domain property mus be of type string. But I never use this for connection with any other tool. Ok. With sql query I get my domain name:
`SELECT DEFAULT_DOMAIN()[DomainName]`
It is: WORKGROUP

But if I put this in config, I get another error, but now from my SQL server, this domain not exists. I think there is something wrong with domains. By default it is not required.

Error output:
`Request connection/ConnectRequest received
(node:9796) UnhandledPromiseRejectionWarning: ConnectionError: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
    at Connection.tedious.once.err (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:109190:17)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Connection.processLogin7NTLMAck (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:112268:14)
    at Connection.message (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:112824:14)
    at Connection.dispatchEvent (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:111927:36)
    at MessageIO.messageIo.on (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:111827:14)
    at MessageIO.emit (events.js:182:13)
    at Message.message.on (c:\Users\Profesor08\.vscode\extensions\mtxr.sqltools-0.17.13\languageserver.js:148924:14)
    at Message.emit (events.js:187:15)
(node:9796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)`

**Comment by mtxr** [comment]
@Profesor08 can you share you connection object (in settings.json file)?

We have a prop that I believe it's set when it shouldn't. See:
```json
{
  "name": "MSSQL",
  "server": "localhost",
  "dialect": "MSSQL",
  "port": 1433,
  "database": "test_db",
  "username": "sa",
  "domain": null, // <---- this prop should be null or WORKGROUP
  "askForPassword": false,
  "password": "root(!)Password",
  "connectionTimeout": 15
```

**Comment by mtxr** [comment]
Guys, please try v0.17.4. I believe all issues related here were fixed (maybe not $$ issue).

**Comment by Profesor08** [comment]
```
{
  "sqltools.connections": [
    {
      "askForPassword": false,
      "connectionTimeout": 30,
      "database": "MuOnline",
      "dialect": "MSSQL",
      "domain": null,
      "name": "SQL Express (no domain)",
      "password": "123456",
      "port": 1433,
      "server": "127.0.0.1",
      "username": "profesor08"
    },
    {
      "askForPassword": false,
      "connectionTimeout": 30,
      "database": "MuOnline",
      "dialect": "MSSQL",
      "domain": "WORKGROUP",
      "name": "SQL Express (with domain)",
      "password": "123456",
      "port": 1433,
      "server": "127.0.0.1",
      "username": "profesor08"
    }
  ]
}
```

**Comment by mtxr** [comment]
Is it working with version 0.17.4?

**Comment by Profesor08** [comment]
Yes

**Comment by briansix** [comment]
Connections are working for me

**Comment by mtxr** [comment]
Thanks you @Profesor08 and @briansix .

If you like the project, consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
