### ISSUE TITLE
PostgreSQL error showing `relation "--" does not exist` on `Show table records`

### ISSUE THREAD

**Issue by gulshan** [mtxr/vscode-sqltools#216]
**Describe the bug**
On `Show table records` command in PostgreSQL error showing `relation "public.aspnetuserroles" does not exist` 

**To Reproduce**
1. Connect to a Postgresql DB
2. Go to any table
3. Right click on table name
4. Select `Show table records`
5. See error-
```cmd
INFO: Executing SQLTools.showRecords
ERROR: Error:  relation "public.aspnetuserroles" does not exist
ERROR: Error:  { [Error: relation "public.aspnetuserroles" does not exist
	at handleResponse (C:\Users\User1\.vscode\extensions\mtxr.sqltools-0.18.0\extension.js:2164:48)
	at processMessageQueue (C:\Users\User1\.vscode\extensions\mtxr.sqltools-0.18.0\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\User1\.vscode\extensions\mtxr.sqltools-0.18.0\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)]
  code: -32001,
  data: { dialect: 'PostgreSQL', dialectOptions: {} } }
```

**Expected behavior**
See the records from the selected table.

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version: 0.18.0
 - VSCode Version: 1.33.1
 - Dialect Used: PostgreSQL
 - OS: Windows

**Additional context**
The name of the table was `AspNetUserRoles`. But it seems SQLTools is using the lowercase version `public.aspnetuserroles`. This may cause the error.

**Comment by mtxr** [comment]
Hi @gulshan, 

We are not chaning the case of the table. Might be something else this error. Even though take a look https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/

Could you share an screenshot of your Tree view?  Also here is it working with both table names, i've created one without double quoting and another with quoutes "AspNetUserRoles".

https://imgur.com/DXWXubo

Let me know how it goes.

**Comment by gulshan** [comment]
Then may be casing is not the problem. Other actions like `Describe table` and `Generate insert query` are working without any problem. The database is a typical ASP.NET core "identity" database generated by the framework. Here is the tree view-

![Annotation 2019-05-08 164241](https://user-images.githubusercontent.com/751732/57369823-61c51700-71b0-11e9-8ed0-c2eb0d0c5d12.png)

**Comment by gulshan** [comment]
It is working now with the new version. Thanks.

**Comment by mtxr** [comment]
You are welcome @gulshan!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
