### ISSUE TITLE
Exception when connecting/changing connection not from an SQL file created from the sidebar

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#236]
Post the v0.19 changes for file sessions, There seems to be an issue using the `SQLTools: Connect` command. If you are not using the sidebar to create the SQL file/tab, Trying to connect throws the following exception:

```
ERROR: Error:  [TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at assertPath (path.js:39:11)
	at Object.join (path.js:434:7)
	at ConnectionManagerPlugin.<anonymous> (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29412:75)
	at Generator.next (<anonymous>)
	at module.exports.__awaiter (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29135:71)
	at new Promise (<anonymous>)
	at module.exports.__awaiter (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29131:12)
	at ConnectionManagerPlugin.openConnectionFile (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29407:16)
	at ConnectionManagerPlugin.<anonymous> (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29219:32)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\ran\.vscode\extensions\mtxr.sqltools-0.19.0\extension.js:29132:58)]
```

**To Reproduce**
1. Open VSCode.
2. Create a new file or change the existing Untitled tab to be an SQL file via the language choice command/UI.
3. Invoke the `SQLTools: Connect` command.
4. See error in notification/log.

**Expected behavior**
Connection will be succesfull and should be attached to the current file.

**Desktop (please complete the following information):**
 - SQLTools Version v0.19.0
 - VSCode Version: v1.34
 - Dialect Used: MSSQL
 - OS: Windows 10 Pro x64 Build 1903

**Comment by mtxr** [comment]
Confirmed. Happens when no folder is open..

**Comment by ransagy** [comment]
Confirmed, working well now. Thanks!
