### ISSUE TITLE
MYSQL Timeout When connecting using account that have access to massive table and DB

### ISSUE THREAD

**Issue by benyaminl** [mtxr/vscode-sqltools#240]
**Describe the bug**
Lately, since 1.17.4, connection to localhost using mysql driver is hard to be done, and always takes soooo long time to connect, not like previous version. It can be the driver problem, but I can't prove it now. 

**To Reproduce**
1. Connect to DB
2. Waited (1-2 minutes, it's localhost and it's very strange)
3. Connection established
4. Suddenly error occur, connection timeout.

**Expected behavior**
Normally connect and ready to do query

**Screenshots**
![image](https://user-images.githubusercontent.com/2817332/58063808-fdd82080-7ba9-11e9-975d-a49f55a35efc.png) From the MySQL console.

**Desktop (please complete the following information):**
 - SQLTools Version [v0.18.2]
 - VSCode Version: [1.3.4]
 - Dialect Used: [MySQL]
 - OS: [Windows 10 1809, May Update 2019]

**Additional context**
The error console shown this.
```json
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
DEBUG: Configs reloaded!
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
INFO: Executing SQLTools.selectConnection
DEBUG: Configs reloaded!
DEBUG: Configs reloaded!
DEBUG: Configs reloaded!
DEBUG: Configs reloaded!
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
ERROR: Error:  Handshake inactivity timeout
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
ERROR: Error:  Handshake inactivity timeout
WARN: rejected promise not handled within 1 second: Error: Handshake inactivity timeout
WARN: stack trace: Error: Handshake inactivity timeout
	at handleResponse (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (C:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
INFO: Executing SQLTools.showOutputChannel
```

**Comment by benyaminl** [comment]
Anyway as I look into it, it's query all the database columns and table, 2nd weird problem is I set the database I want to connect, it show all other database, maybe it's the root of the problem, because this database is quite heavy, and It's and ERP Database. It's from Dolibarr Project.

**Comment by benyaminl** [comment]
@mtxr is it only me or this also effect other people?

**Comment by mtxr** [comment]
@benyaminl I'll check it deeper. Still don't have this answer right now.

I'll take a look on it later today, together with #238.

They are not really related (at least in a first look), but I plan to fix both today/tomorrow

**Comment by mtxr** [comment]
@benyaminl does it still happens on new versions?

**Comment by benyaminl** [comment]
For now It's not, 
I can't confirm more for now because sometimes the problem exist and sometimes not. 
Anyway about only show the database that's defined on the connection, when will it implemented? Now every database that's assigned to that account is shown on the pannel cause slowdown. 

On Wed, 26 Jun 2019 05:08:53 -0700
Matheus Teixeira <notifications@github.com> wrote:

> @benyaminl does it still happens on new versions?
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mtxr/vscode-sqltools/issues/240#issuecomment-505846992


-- 
Regrads,
Benyamin Limanto
sent with Sylpheed from ThinkPad X240 on CENTOS 7

**Comment by benyaminl** [comment]
> @benyaminl does it still happens on new versions?

Happened again if the database is hugh, 
![image](https://user-images.githubusercontent.com/2817332/60390665-a365a480-9b05-11e9-8225-75f02ddfbe10.png)

```
Error:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174399:15)
    at Handshake.emit (events.js:182:13)
    at Handshake._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:24895:8)
    at Timer._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:181457:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol.module.exports.Protocol._enqueue (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174385:48)
    at Protocol.handshake (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174287:23)
    at PoolConnection.connect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45213:18)
    at Pool.module.exports.Pool.getConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93494:16)
    at Pool.releaseConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93613:10)
    at Pool.module.exports.Pool._removeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93724:8)
    at Pool._purgeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93707:8)
    at Ping.onOperationComplete (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93552:12)
    at Ping.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45618:10)
    at Ping._callback (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45584:16)
  code: -32001,
  data:
   { dialect: 'MySQL',
     dialectOptions:
      { mssqlOptions: undefined,
        mysqlOptions: undefined,
        pgOptions: undefined,
        oracleOptions: undefined } },
  name: 'Error' }
Error:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174399:15)
    at Handshake.emit (events.js:182:13)
    at Handshake._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:24895:8)
    at Timer._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:181457:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol.module.exports.Protocol._enqueue (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174385:48)
    at Protocol.handshake (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174287:23)
    at PoolConnection.connect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45213:18)
    at Pool.module.exports.Pool.getConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93494:16)
    at Pool.releaseConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93613:10)
    at Pool.module.exports.Pool._removeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93724:8)
    at Pool._purgeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93707:8)
    at Handshake.onConnect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93505:14)
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45618:10)
    at Handshake._callback (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45584:16)
  code: -32001,
  data:
   { dialect: 'MySQL',
     dialectOptions:
      { mssqlOptions: undefined,
        mysqlOptions: undefined,
        pgOptions: undefined,
        oracleOptions: undefined } },
  name: 'Error' }
Request connection/RefreshAllRequest received
Error:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174399:15)
    at Handshake.emit (events.js:182:13)
    at Handshake._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:24895:8)
    at Timer._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:181457:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol.module.exports.Protocol._enqueue (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174385:48)
    at Protocol.handshake (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174287:23)
    at PoolConnection.connect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45213:18)
    at Pool.module.exports.Pool.getConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93494:16)
    at Pool.releaseConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93613:10)
    at Pool.module.exports.Pool._removeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93724:8)
    at Pool._purgeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93707:8)
    at Handshake.onConnect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93505:14)
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45618:10)
    at Handshake._callback (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45584:16)
  code: -32001,
  data:
   { dialect: 'MySQL',
     dialectOptions:
      { mssqlOptions: undefined,
        mysqlOptions: undefined,
        pgOptions: undefined,
        oracleOptions: undefined } },
  name: 'Error' }
Request connection/RefreshAllRequest received
Error:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174399:15)
    at Handshake.emit (events.js:182:13)
    at Handshake._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:24895:8)
    at Timer._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:181457:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol.module.exports.Protocol._enqueue (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174385:48)
    at Protocol.handshake (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174287:23)
    at PoolConnection.connect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45213:18)
    at Pool.module.exports.Pool.getConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93494:16)
    at Pool.releaseConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93613:10)
    at Pool.module.exports.Pool._removeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93724:8)
    at Pool._purgeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93707:8)
    at Handshake.onConnect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93505:14)
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45618:10)
    at Handshake._callback (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45584:16)
  code: -32001,
  data:
   { dialect: 'MySQL',
     dialectOptions:
      { mssqlOptions: undefined,
        mysqlOptions: undefined,
        pgOptions: undefined,
        oracleOptions: undefined } },
  name: 'Error' }
Error:  { Error: Handshake inactivity timeout
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174399:15)
    at Handshake.emit (events.js:182:13)
    at Handshake._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:24895:8)
    at Timer._onTimeout (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:181457:23)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol.module.exports.Protocol._enqueue (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174385:48)
    at Protocol.handshake (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:174287:23)
    at PoolConnection.connect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45213:18)
    at Pool.module.exports.Pool.getConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93494:16)
    at Pool.releaseConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93613:10)
    at Pool.module.exports.Pool._removeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93724:8)
    at Pool._purgeConnection (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93707:8)
    at Handshake.onConnect (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:93505:14)
    at Handshake.<anonymous> (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45618:10)
    at Handshake._callback (c:\Users\Ben\.vscode\extensions\mtxr.sqltools-0.19.6\languageserver.js:45584:16)
  code: -32001,
  data:
   { dialect: 'MySQL',
     dialectOptions:
      { mssqlOptions: undefined,
        mysqlOptions: undefined,
        pgOptions: undefined,
        oracleOptions: undefined } },
  name: 'Error' }

```

**Comment by benyaminl** [comment]
It even cause server running some query for non sense
![image](https://user-images.githubusercontent.com/2817332/60390692-6817a580-9b06-11e9-9778-df6e1826d868.png)
![image](https://user-images.githubusercontent.com/2817332/60390698-92696300-9b06-11e9-8d53-18f3e3cfa461.png)
see th traffic, seems the way you query it cause some problem for massive database. 
Hmm...

**Comment by mtxr** [comment]
Thanks @benyaminl! 

I'll do some changes to workaround this. You did a pretty great job digging into it

**Comment by mtxr** [comment]
Closing in favor of #322.
