### ISSUE TITLE
npm link before npm install

### ISSUE THREAD

**Issue by ariel-bentu** [mtxr/vscode-sqltools#274]
**Is your feature request related to a problem? Please describe.**
In some cases, you'd like to deliver a fully working set of tools at once. now, with vscode remote container, it gets more clear how.
In such cases you may want to pre-install the dialect's driver.
To do so, you may run npm install -g <driver> on the Dockerfile build. 

I'm looking for a way to tell sqltools to use the globally installed driver.

**Describe the solution you'd like**
When sqltools identifies a missing dependency, before asking the use, it will attemp to run npm link. This will succeed in case the driver is installed globally. in the event of success - proceed, no user interaction. if fails, ask the use to install.

If this way is acceptable, I will be happy to create a pull request with it.

**Describe alternatives you've considered**
none
**Additional context**
https://docs.npmjs.com/cli/link

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!

**Comment by mtxr** [comment]
@ariel-bentu what happend if the linekd version is not compatible with the extension?

That's my only concern. I set an exact version to be used with SQLTools, but I can't guarantee that it will work with a linked version.

Any suggestions?

**Comment by ariel-bentu** [comment]
as you may see in the documentation, the command allows specifying version as well:
npm link [<@scope>/]<pkg>[@<version>]

when testing it, I noticed that if it is missing, it installs it (npm install). which is not good for our case.

So the way I found is the following:
-> in the dependency manager can't find the package, before asking the user to install, it executes:
npm list -g <pkg>@<version>
if the package exists in the global with the right version the output would be :
/the/global/path
└── <pkg...>

or 
/the/global/path
└── (empty)

if it exists, run npm link. if not, prompt the user to install

what do you say?

**Comment by xarielx** [comment]
I have the same issue, it does not let me use the feauture to show the dependencies, am I doing something wrong? @ariel-bentu @mtxr 

DEBUG: Settings updated!
INFO: Telemetry enabled!
DEBUG: Event: sessionStarted:extension 
DEBUG: Activation time: 16.2897ms
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Request DependencyInstaller/install failed with message: You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
	at handleResponse (,,,\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:918:48)
	at processMessageQueue (,,,9\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:745:17)
	at Immediate.module.exports.setImmediate (\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:729:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Request DependencyInstaller/install failed with message: You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
	at handleResponse (\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:918:48)
	at processMessageQueue (\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:745:17)
	at Immediate.module.exports.setImmediate (\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:729:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Request DependencyInstaller/install failed with message: You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
	at handleResponse (...\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:918:48)
	at processMessageQueue (\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:745:17)
	at Immediate.module.exports.setImmediate (...\.vscode\extensions\mtxr.sqltools-0.19.6\extension.js:729:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel

**Comment by ariel-bentu** [comment]
Your issue seems to be connected that npm itself cannot run to install the
dependency. It assumes node and npm to be present on your machine...

בתאריך יום ה׳, 11 ביולי 2019, 17:54, מאת Ariel Barboza ‏<
notifications@github.com>:

**Comment by mtxr** [comment]
@ariel-bentu you are right.

@xarielx please install nodeJS and it should work just fine.

Closing.
