### ISSUE TITLE
SAP HANA connection fails

### ISSUE THREAD

**Issue by shivangag** [mtxr/vscode-sqltools#338]
Error log:

> 
> INFO: Executing SQLTools.openEditConnectionScreen
> INFO: Executing SQLTools.updateConnection
> DEBUG: Settings updated!
> DEBUG: Connection explorer updated.
> INFO: Executing SQLTools.selectConnection
> ERROR: Error:  { [Error: only secure connections are allowed
> 	at C:\Users\*****\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:22983
> 	at C:\Users\*****\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:23390
> 	at Immediate.module.exports.messageQueue.size.setImmediate (C:\Users\*****\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:23934)
> 	at runCallback (timers.js:694:18)
> 	at tryOnImmediate (timers.js:665:5)
> 	at processImmediate (timers.js:647:5)] code: 4321, data: { dialect: 'SAPHana', dialectOptions: {} } }

Connection setting:
```
{
  "name": "SDI Server DB",
  "dialect": "SAPHana",
  "server": "zeus.hana.*****.***-***-1.*****.dbaas.ondemand.com",
  "port": 20957,
  "database": "8D0571B**********6AFE72",
  "username": "8D0571B********************RT",
  "askForPassword": true,
  "connectionTimeout": 30
}
```

**Comment by mtxr** [comment]
@ariel-bentu do you have any idea or tips for @shivangag ?

**Comment by ariel-bentu** [comment]
Hi,

try this code with Node.js and see if it works regardless SQLTools. I would suspect it has something to do with network visibility to you HANA server

```
const hanaClient = require("@sap/hana-client");

var client = hanaClient.createClient({
    host: '<Your host',
    port: '<your port>',
    user: 'user',
    password: 'pwd'
});

client.connect(function (err) {
    if (err) {
        return console.error("Connection error", err);
    }
    console.log("Connected to SAP HANA");

    console.log("Executing 'select 'isConnected' as Connection_Status from dummy'");

    client.exec("select 'isConnected' as Connection_Status from dummy", (err, rows) => {
        if (err) {
            return console.error("Connection error", err);
        }
        console.log("Results: ");
        console.log(JSON.stringify(rows));
    });
});


```

**Comment by ariel-bentu** [comment]
Hi,
I found that the HANA as a service requires ssl. and I saw that I did not allow easy passing of other connection options, so I now added them in a PR: https://github.com/mtxr/vscode-sqltools/pull/346

So now for it to work, add 
```
{
  "name": "SDI Server DB",
  "dialect": "SAPHana",
  "server": "zeus.hana.*****.***-***-1.*****.dbaas.ondemand.com",
  "port": 20957,
  "database": "8D0571B**********6AFE72",
  "username": "8D0571B********************RT",
  "askForPassword": true,
  "connectionTimeout": 30
  "hanaOptions": {
    "ENCRYPT": true,
    "sslValidateCertificate": false
  }
```

if you wish to verify ssl-server-cert, you'd need to follow the instruction in /docs/Connections/SAPHANA.md regarding trust-store. (until PR is accepted, you can see it here:
https://github.com/ariel-bentu/vscode-sqltools/blob/hanaoptions/docs/Connections/SAPHANA.md)
