### ISSUE TITLE
Error opening connection with SQLite

### ISSUE THREAD

**Issue by luiz-rocha** [mtxr/vscode-sqltools#367]
**Describe the bug**
After installation and creation of a connection, it was working fine.
Then I needed to change my project's directory, and now SQLtools can't connect anymore to the same SQLite database file.

**To Reproduce**
1. Add new connection

2. Fill data
2.1 Connection name: MyDB
2.2 Dialects: SQLite (Node Native)
2.3 Database: mydb.db

3. Click on CREATE
4. Click on Connect Now
5. See Error

**Expected behavior**
Create a database connection.

**Desktop:**
 - SQLTools Version: v0.20.3
 - VSCode Version: 1.37.1
 - Dialect Used/Version: SQLite
 - OS: Windows 10

**Error Message**
```
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { Error: SQLITE_CANTOPEN: unable to open database file
    at c:\Users\User\.vscode\extensions\mtxr.sqltools-0.20.3\extension.js:1:22921
    at c:\Users\User\.vscode\extensions\mtxr.sqltools-0.20.3\extension.js:1:23328
    at Immediate.module.exports.messageQueue.size.setImmediate (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.20.3\extension.js:1:23872)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
  code: -32001,
  data: { dialect: 'SQLite', dialectOptions: {} } }
```

**Additional Info**
I've checked file-system permissions
Uninstalled SQLTools
Deleted c:\Users\User\.vscode\extensions\mtxr.sqltools-0.20.3
Reinstalled

Same issue

**Comment by luiz-rocha** [comment]
Hey, problem solved.

If someone comes up with the same problem, do as follows:

1. Open `%appdata%\Code\Workspaces\`
You'll see a folder with some big number
2. Enter this folder and open workspace.json
3.Locate  **"sqltools.connections"** and edit **"database"** with the absolute path to your sqlite db:

this:

> **"database": ".\\db\\mydb.sqlite3",**

to something like this:

>  **"database": "C:/web/my-project/db/mydb.sqlite3",**
