### ISSUE TITLE
Error opening Oracle connection on MacOS 10.14.5

### ISSUE THREAD

**Issue by BrightSchema** [mtxr/vscode-sqltools#382]
**Bug**
After creating the connection, any attempt to connect is met with this error message.
```
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): Library not loaded: /ade/dosulliv_ldapmac/oracle/ldap/lib/libnnz11.dylib
  Referenced from: /usr/local/lib/libclntsh.dylib
  Reason: image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the 64-bit Oracle Instant Client Basic or Basic Light package in ~/lib or /usr/local/lib
They can be downloaded from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
	at /Users/duketrammell/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:22983
	at /Users/duketrammell/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:23390
	at Immediate.module.exports.messageQueue.size.setImmediate (/Users/duketrammell/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:23934)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -1, data: { dialect: 'OracleDB', dialectOptions: {} } }
```
**Desktop (please complete the following information):**
 - SQLTools Version v0.20.3
 - VSCode Version: v12.10.0
 - Dialect Used/Version: Oracle CE
 - OS: Mac

**Comment by BrightSchema** [comment]
And `libclntsh.dylib` does exist in `/usr/local/lib`

```
duketrammell@lift ~ l /usr/local/lib/ | grep clntsh
lrwxr-xr-x    1 duketrammell  admin    27B Sep 16 15:22 libclntsh.dylib -> /opt/oracle/libclntsh.dylib
duketrammell@lift ~ l /opt/oracle
total 478248
lrwxr-xr-x@  1 duketrammell  staff    20B Sep 16 15:12 libclntsh.dylib -> libclntsh.dylib.19.1
-rwxr-xr-x@  1 duketrammell  staff   1.5M Jul  5 09:22 libocci.dylib.19.1
```
The other basic package files in `/opt/oracle also exist, but were omitted because it was hard to read.

**Comment by BrightSchema** [comment]
After overwriting the `libclntsh.dylib` in `/usr/local/lib` to the one downloaded and placed in `/opt/oracle` (`libocci.dylib.19.1`) it now works.
