### ISSUE TITLE
Could not connect (sequence)

### ISSUE THREAD

**Issue by richarddavenport** [mtxr/vscode-sqltools#59]
### Issue Type

* [ ] Feature Request
* [X] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [X] Did you check the logs?
* [X] Did you check the Setup?

### Description

I'm installing and trying to connect for the first time and I'm getting the error below.

### Steps to Reproduce (For bugfixes)

1. Installed Extension
2. Added a connection to MSSQL Server
3. Try to connect

**Expected behavior:**

Connected to DB

**Actual behavior:** 

`Failed to connect to dev-sql003:3306 - Could not connect (sequence)`

```
[2018-01-19T20:38:00.][v0.11.4] INFO: Telemetry enabled!
[2018-01-19T20:38:00.][v0.11.4] INFO: Configuration set to auto connect to: null
[2018-01-19T20:38:00.][v0.11.4] INFO: Language server started in 330.387669ms
[2018-01-19T20:38:07.][v0.11.4] ERROR: Error while preparing columns completions
[2018-01-19T20:38:07.][v0.11.4] {"code":"ESOCKET","originalError":{"message":"Failed to connect to dev-sql003:3306 - Could not connect (sequence)","code":"ESOCKET"},"name":"ConnectionError"}
[2018-01-19T20:38:07.][v0.11.4] ERROR: Failed to prepare sidebar itens
[2018-01-19T20:38:07.][v0.11.4] {"code":"ESOCKET","originalError":{"message":"Failed to connect to dev-sql003:3306 - Could not connect (sequence)","code":"ESOCKET"},"name":"ConnectionError"}
[2018-01-19T20:38:07.][v0.11.4] ERROR: Error selecting connection: 
[2018-01-19T20:38:07.][v0.11.4] Error: Failed to connect to dev-sql003:3306 - Could not connect (sequence)
	at Connection.base.ConnectionPool._poolCreate.base.Promise.tedious.once.err (/Users/richard/.vscode-insiders/extensions/mtxr.sqltools-0.11.4/node_modules/mssql/lib/tedious.js:216:17)
	at Object.onceWrapper (events.js:293:19)
	at emitOne (events.js:96:13)
	at Connection.emit (events.js:191:7)
	at Connection.socketError (/Users/richard/.vscode-insiders/extensions/mtxr.sqltools-0.11.4/node_modules/tedious/lib/connection.js:699:14)
	at /Users/richard/.vscode-insiders/extensions/mtxr.sqltools-0.11.4/node_modules/tedious/lib/connection.js:590:25
	at SequentialConnectionStrategy.connect (/Users/richard/.vscode-insiders/extensions/mtxr.sqltools-0.11.4/node_modules/tedious/lib/connector.js:153:9)
	at Socket.onError (/Users/richard/.vscode-insiders/extensions/mtxr.sqltools-0.11.4/node_modules/tedious/lib/connector.js:169:16)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
```

### Versions

- *Version*: v0.11.4
- *OS*: macOS 10.13.2
- *SGDB*: MSSQL

**Comment by mtxr** [comment]
Could you please provide you connections settings? (Without passwords of course)

Also, try to connect using some cli or other tool to see what happens.

**Comment by richarddavenport** [comment]
@mtxr not using a connection string, or at least I'm not providing one. I use the sql tools prompt for creating a connection, I have the following in my workspace settings:
``` json
"sqltools.connections": [
        {
            "name": "dev-sql003",
            "server": "dev-sql003",
            "dialect": "MSSQL",
            "port": 3306,
            "database": "HCCPProd",
            "username": "sa",
            "askForPassword": false,
            "password": "",
            "connectionTimeout": 15
        }
    ]
```
I do use the mssql extension and use this as my connection setting and it connects:
``` json
"mssql.connections": [
        {
            "server": "dev-sql003",
            "database": "HCCPProd",
            "user": "sa",
            "password": "",
            "connectTimeout": 15,
            "encrypt": false,
            "applicationName": "vscode-mssql",
            "authenticationType": "SqlLogin"
        }
    ]
```

**Comment by richarddavenport** [comment]
Okay, so I stupidly let the port autofill for me and forgot that mssql uses 1433 for the port not 3306. However I was still getting a timeout error, which I fixed by increasing the timeout.

As a feature request, you could we get the port to autofill to the correct default port when changing "dialects" in the connection creation wizard?

**Comment by Jeordie** [comment]
Where or how can i check  the log?

**Comment by richarddavenport** [comment]
@Jeordie Open up the Output panel (shift + cmd/ctrl + U) and select the sql tools output:
<img width="758" alt="screen shot 2018-01-31 at 9 35 07 am" src="https://user-images.githubusercontent.com/3596012/35631716-38b03c08-066a-11e8-9a5b-de1bec183d84.png">

**Comment by Jeordie** [comment]
Thanks @richarddavenport

**Comment by mtxr** [comment]
Seems that we should let user set an option to use SSL or not during the connection. It's an enhancement.
Thank you @richarddavenport .

**Comment by mtxr** [comment]
Duplicate #60.
