### ISSUE TITLE
SQLite3 connection not responding.

### ISSUE THREAD

**Issue by UchidaHitoshi** [mtxr/vscode-sqltools#616]
**Describe the bug**
After connecting to a database file with SQLite driver, when manipulating the tree view in Connections, a rotating symbol display in front of a Tables icon and the tables and views cannot be displayed.

Run "Run selected query" from  .session.sql in the editor. also only display a rotating symbol in the "SQLTools Results" window and no response.

**To Reproduce**
	1. Clean install VS Code and Node.js
	2. install SQLTools and SQLite driver
	3. set sqltools.useNodeRuntime to  true and reload window
	4. Setup db connection and connect to db. (and install node module sqlite3@4.2.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/1044061/84221425-2c57cf00-ab10-11ea-9513-4b704b82b762.png)

**Desktop (please complete the following information):**

	- VS Code	1.45.1
	- SQLTools	0.22.7
	- SQLTools SQLite	0.0.5
	- Node.js		12.8.0
	- Windows 10		10.0.17763.973

**Additional context**
#setting.json
```
    "sqltools.useNodeRuntime": true,
    "sqltools.connectionExplorer.groupConnected": true,
    "sqltools.connections": [
        {
            "database": "C:\\Users\\me\\Desktop\\sampledb.db",
            "driver": "SQLite",
            "name": "SAMPLEDB",
            "previewLimit": 50
        }
    ],
```

#SQLTool Log:
```
['ls:info'] SQLTools Server started!
===============================
Using node runtime?: yes
ExecPath: C:\Program Files\nodejs\node.exe v12.18.0
===============================
['ext:lc:info'] LanguageClient ready
namespaces set to  *,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
['ls:info'] request to register plugin: "c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js"
['ls:ls-context:register-driver'] Driver sqlite registered!
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.openAddConnectionScreen
['ext:main:info'] EXECUTING => sqltools.testConnection
['driver:require'] Resolve module C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3\package.json
['ext:main:info'] EXECUTING => sqltools.addConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
namespaces set to  *,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ls:cache:query-results:info'] DELETE keys starting with [SAMPLEDB|SQLite||C:\Users\me\Desktop\sampledb:db]...
['ls:cache:query-results:info'] DELETE keys starting with [SAMPLEDB|SQLite||C:\Users\me\Desktop\sampledb:db] completed!
['ls:cache:manager:info'] DELETE keys starting with [SAMPLEDB|SQLite||C:\Users\me\Desktop\sampledb:db]...
['ls:cache:manager:info'] DELETE keys starting with [SAMPLEDB|SQLite||C:\Users\me\Desktop\sampledb:db] completed!
['driver:require'] Resolve module C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3\package.json
['ext:main:info'] EXECUTING => sqltools.getConnections
['ls:dep-man:info'] Will install sqlite3 package 

> sqlite3@4.2.0 install C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
needle Making request #1 {
  localAddress: undefined,
  protocol: 'https:',
  host: 'mapbox-node-binary.s3.amazonaws.com',
  port: 443,
  path: '/sqlite3/v4.2.0/node-v72-win32-x64.tar.gz',
  method: 'get',
  headers: {
    accept: '*/*',
    'user-agent': 'node-pre-gyp (v0.11.0, npm/6.14.4 node/v12.18.0 win32 x64)',
    host: 'mapbox-node-binary.s3.amazonaws.com'
  }
}
needle Got response 200 {
  'x-amz-id-2': 'xLPDXT/ze6dzlXDsMj16C5bdL03HHpHTYhvn6OLpkxj0VQYvCBOHSpUNpaSuo3mV+qQT2mvi4mI=',
  'x-amz-request-id': 'C823924C7D1D1892',
  date: 'Wed, 10 Jun 2020 01:54:28 GMT',
  'last-modified': 'Tue, 21 Apr 2020 19:31:51 GMT',
  etag: '"4de0c8d837ee8f5af5830164aa44c2c1"',
  'accept-ranges': 'bytes',
  'content-type': 'application/octet-stream',
  'content-length': '927061',
  server: 'AmazonS3',
  connection: 'close'
}
[sqlite3] Success: "C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\me\AppData\Local\vscode-sqltools\Data\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\me\AppData\Local\vscode-sqltools\Data\package.json'
npm WARN Data No description
npm WARN Data No repository field.
npm WARN Data No README data
npm WARN Data No license field.

+ sqlite3@4.2.0
updated 1 package and audited 110 packages in 4.508s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

['ls:dep-man:info'] Finished sqlite3 script
['ls:dep-man:info'] Finished installing deps
['ext:main:info'] EXECUTING => sqltools.getChildrenForTreeItem
['ext:main:info'] EXECUTING => sqltools.refreshTree
['ext:main:info'] EXECUTING => sqltools.getChildrenForTreeItem
['ext:main:info'] EXECUTING => sqltools.getChildrenForTreeItem
['driver:require'] Require module C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3
(node:72372) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\Users\me\AppData\Local\vscode-sqltools\Data\node_modules\sqlite3'
    at webpackEmptyContext (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:209246)
    at Object._sqltoolsRequire [as default] (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:47662)
    at SQLite.get lib [as lib] (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:58716)
    at db (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:58892)
    at new Promise (<anonymous>)
    at SQLite.open (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:58832)
    at async SQLite.query (c:\Users\me\.vscode\extensions\mtxr.sqltools-driver-sqlite-0.0.5\out\ls\plugin.js:1:58095)
(node:72372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:72372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rustnnes** [comment]
Same issue here, but on a linux box.

Node v12.18
Code v1.46

**Comment by nonameolsson** [comment]
Same here.

Node v12.18
Code v1.46

**Comment by mtxr** [comment]
Fixed on the latest version of the drivers
