### ISSUE TITLE
Receiving Error "Error selecting connection Error: Connection got disposed." when connecting to MSSQL Server using integrated security

### ISSUE THREAD

**Issue by EdBrereton** [mtxr/vscode-sqltools#70]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ ] Feature Request
* [X] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [X] Did you check the logs?
* [X] Did you check the Setup?

### Description

When attempting to connect to a MS SQL Server I get the error message in the title and the following logs are produced

````
[2018-03-09T14:40:54.][v0.12.1] ERROR: Error selecting connection: 
[2018-03-09T14:40:54.][v0.12.1] Error: Connection got disposed.
	at Object.dispose (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
````

### Steps to Reproduce (For bugfixes)

1. Configure a connection for an MSSQL Server with a config similar to below (sanitized)
2. Try and connect

````
"sqltools.connections": [
			{
				"name": "db",
				"server": "db",
				"dialect": "MSSQL",
				"port": 1433,
				"database": "someDb",
				"username": "ejbrer",
				"askForPassword": false,
				"password": null,
				"domain": "domain",
				"connectionTimeout": 15
			}
````

**Expected behavior:** [What you expected to happen]

The software to connect to the database

**Actual behavior:** [What actually happened]

An error is displayed and the software is not connected to the database

### Versions

- *Version*: v0.12.1
- *OS*: Windows 10
- *SGDB*: MS SQL Server 2012

You can get this information from executing `SQLTools: Version` from VSCode `Quick Open`.

**Comment by Jeordie** [comment]
I'm getting the same error, see my comments on closed issue [#67](https://github.com/mtxr/vscode-sqltools/issues/67)

**Comment by mtxr** [comment]
I'll be fixed soon. Sorry for my late reply guys. I'm in a hurry here

**Comment by mtxr** [comment]
@EdBrereton 
Can you please update VSCODE to v1.19+? It should work.

@Jeordie you can try again to check if it works

**Comment by EdBrereton** [comment]
@mtxr I have just updated to VS Code V1.21.1 and still have the same error

```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

```
[2018-03-20T14:31:47.][v0.12.1] ERROR: Error selecting connection: 
[2018-03-20T14:31:47.][v0.12.1] Error: Connection got disposed.
	at Object.dispose (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\ejbrer\.vscode\extensions\mtxr.sqltools-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
[2018-03-20T14:32:15.][v0.12.1] INFO: Using SQLTools v0.12.1
```

**Comment by Jeordie** [comment]
@mtxr I'm getting the exact error as stated by @EdBrereton

**Comment by mtxr** [comment]
Still happening?

**Comment by Jeordie** [comment]
Yes still the same error

**Comment by EdBrereton** [comment]
Ditto. Same for me.

**Comment by mtxr** [comment]
Did the version v0.15 resolved this issue?

To be honest, I still trying to reproduce it locally, but no success.

**Comment by Jeordie** [comment]
Nope, unfortunately still the same problem

**Comment by mtxr** [comment]
This has already been changed as seen on #155.

I'll be closing, it will be released soon.
