### ISSUE TITLE
SQLTools crashes

### ISSUE THREAD

**Issue by cheasea** [mtxr/vscode-sqltools#909]
**Describe the bug**
When I try to launch VS Code with SQLTools enabled, the plugin crashes.

**Desktop (please complete the following information):**
 - VSCode Version: 1.68.0
 - OS: Windows 7

**Additional context**
Here is my logs.
```
[1655090020164] INFO  (ext): SQLTools is starting
[1655090020175] INFO  (ext): initializing language client...
[1655090020721] INFO  (ext): Registering client for languages [{"scheme":"sqltools"},{"language":"sql","scheme":"untitled"},{"language":"sql","scheme":"file"},{"language":"sql","scheme":"sqltools"}]
    ns: "lc"
[1655090020725] INFO  (ext): loading plugins...
[1655090020725] INFO  (ext): registering Formatter Plugin.
    plugin: {
      "name": "Formatter Plugin"
    }
[1655090020726] INFO  (ext): registering Connection Manager Plugin.
    plugin: {
      "name": "Connection Manager Plugin"
    }
[1655090020726] INFO  (ext): registering CodeLens Plugin.
    plugin: {
      "name": "CodeLens Plugin",
      "registeredLanguages": []
    }
[1655090020728] INFO  (ext): registering Dependency Manager Plugin.
    plugin: {
      "name": "Dependency Manager Plugin",
      "installingDrivers": []
    }
[1655090020731] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1655090020732] INFO  (ext): registering History Manager Plugin.
    plugin: {
      "name": "History Manager Plugin"
    }
[1655090020733] INFO  (ext): registering Bookmarks Manager Plugin.
    plugin: {
      "name": "Bookmarks Manager Plugin"
    }
[1655090020736] INFO  (ext): SQLTools activation completed. 571.408245 ms
[1655090020768] INFO  (ext): Formatter Plugin registered!
[1655090020768] INFO  (ext): CodeLens Plugin registered!
[1655090020769] INFO  (ext): Dependency Manager Plugin registered!
[1655090020769] INFO  (ext): Connection Manager Plugin registered!
[1655090020769] INFO  (ext): History Manager Plugin registered!
[1655090020769] INFO  (ext): Bookmarks Manager Plugin registered!
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:106815)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105434)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105121)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:16:47682)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:100903)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
[Info  - 06:13:41] Connection to server got closed. Server will restart.
[1655090021795] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1655090021796] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:106815)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105434)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105121)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:16:47682)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:100903)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
[Info  - 06:13:41] Connection to server got closed. Server will restart.
[1655090022324] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:106815)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105434)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105121)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:16:47682)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:100903)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
[1655090022785] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[Info  - 06:13:42] Connection to server got closed. Server will restart.
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:106815)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105434)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105121)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:16:47682)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:100903)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
[Info  - 06:13:43] Connection to server got closed. Server will restart.
node:os:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:106815)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105434)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:105121)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:16:47682)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261)
    at Object.<anonymous> (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:22:100903)
    at __webpack_require__ (c:\Users\User\.vscode\extensions\mtxr.sqltools-0.23.0\dist\languageserver.js:1:261) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -4054,
    code: 'ENOSYS',
    message: 'function not implemented',
    syscall: 'uv_os_gethostname'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
[Error - 06:13:44] Connection to server got closed. Server will not be restarted.
[1655090024164] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1655090024182] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1655090024183] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1655090024185] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1655090024188] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
```

**Comment by gjsjohnmurray** [comment]
Does the problem still happen after you update to the latest SQLTools (0.24.0)?

I see you are using Windows 7. The final release of VS Code for that platform is 1.70.3. The latest VS Code (1.71) is not compatible with Windows 7.

**Comment by cheasea** [comment]
Yes, the problem still happens on the version 0.24.0

**Comment by gjsjohnmurray** [comment]
Thanks for checking. I have some more questions:

- Is your Windows 7 32-bit or 64-bit? The info copied from VS Code's Help\About dialog will show us this.
- Does the crash also happen with VS Code 1.70.3?
- Does it happen as soon as you start VS Code after installing the SQLTools extension?
- Does it happen if you disable all other extensions?
- If it happens only when connecting to a database, which driver?

I tested on 32-bit Windows 7 and wasn't able to produce a crash.

**Comment by yugeshwarimonali** [comment]
same error shows in windows 10
