### ISSUE TITLE
All sqltools commands yield command not found

### ISSUE THREAD

**Issue by ilmam** [mtxr/vscode-sqltools#94]
Not sure what's going on. I haven't used sqltools for some time. Now I purchased a new laptop and have a fresh installation of latest vscode.
After adding the sqltools extension, I can't see the connection in the sidebar, and every time I call for any sqltools command like "Setup a connection" or "Connect", an error with message like this (depending on the command): 
command 'SQLTools.setupSQLTools' not found

Please help, I really like this extension and it's a shame that I can't use it any more.

**Comment by ilmam** [comment]
Following is the complete error when showing devtools:

```
Error: command 'SQLTools.selectConnection' not found
    at t._tryExecuteCommand (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2990:488)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2990:343
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at l (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:45)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at l (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:45)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._creator._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at e.resolveOk (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3136:686)
    at e._receiveReply (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3203:856)
    at e._receiveOneMessage (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3203:154)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3202:10
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3205:93
    at e.fire (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:172:532)
    at a (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:307:312)
    at Socket.n._socketDataListener (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:307:531)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:27
e.fire @ event.ts:140
t.notify @ notifications.ts:113
t.error @ notificationService.ts:52
t.onError @ commandsHandler.ts:325
(anonymous) @ commandsHandler.ts:310
done @ winjs.base.js:1399
v @ winjs.base.js:1245
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_chainedError @ winjs.base.js:1052
n @ winjs.base.js:751
then @ winjs.base.js:1457
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
l @ winjs.base.js:1834
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1859
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
e.resolveOk @ lazyPromise.ts:65
e._receiveReply @ rpcProtocol.ts:222
e._receiveOneMessage @ rpcProtocol.ts:180
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
a @ ipc.net.ts:104
n._socketDataListener @ ipc.net.ts:133
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
```
